name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get Information Variables
      id: core
      run: |
        echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
    - name: Compile project
      run: |
        sh build.sh
        cd build
        mkdir vita-toolchain
        make install DESTDIR=../vita-toolchain
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vita-toolchain-${{ steps.core.outputs.sha8 }}
        path: ./vita-toolchain/usr/local/
